-- Migration 010: Create password_reset_otps table for SMS and Gmail OTP Password Resets

CREATE TABLE IF NOT EXISTS public.password_reset_otps (
    otp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES public.accounts(account_id) ON DELETE CASCADE,
    otp_hash VARCHAR(255) NOT NULL,
    channel VARCHAR(20) NOT NULL CHECK (channel IN ('EMAIL', 'SMS')),
    destination VARCHAR(255) NOT NULL,
    reset_token_hash VARCHAR(255),
    attempts INT NOT NULL DEFAULT 0,
    expires_at TIMESTAMPTZ NOT NULL,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_otps_account_id ON public.password_reset_otps(account_id);
CREATE INDEX IF NOT EXISTS idx_otps_reset_token ON public.password_reset_otps(reset_token_hash);
