/* ============================================================
   HỆ THỐNG CHẤM CÔNG NHÂN VIÊN KỸ THUẬT HIỆN TRƯỜNG - PWA
   PostgreSQL - Bản chốt không quản lý ca làm việc

   Phạm vi nghiệp vụ:
   - Quản trị viên chỉ phân công địa điểm chấm công cho nhân viên theo ngày.
   - Không quản lý ca làm việc.
   - Không tính đi trễ hoặc về sớm.
   - Mỗi nhân viên tối đa 01 phân công trong một ngày.
   - Mỗi phân công tương ứng tối đa 01 bản ghi chấm công.
   - Mỗi bản ghi gồm 01 lần check-in và 01 lần check-out.
   - Thời gian chấm công trực tuyến do backend/server ghi nhận.
   - Payload ngoại tuyến có client_request_id để chống xử lý trùng.
   - Nhật ký vị trí lưu snapshot tọa độ mục tiêu và bán kính áp dụng.
   - Các mốc thời gian nghiệp vụ sử dụng TIMESTAMPTZ.
   ============================================================ */

BEGIN;

/* ============================================================
   0. XÓA CẤU TRÚC CŨ
   CẢNH BÁO: Các lệnh này xóa toàn bộ bảng và dữ liệu hiện có.
   ============================================================ */
DROP TABLE IF EXISTS public.system_logs CASCADE;
DROP TABLE IF EXISTS public.employee_face_profiles CASCADE;
DROP TABLE IF EXISTS public.employee_webauthn_credentials CASCADE;
DROP TABLE IF EXISTS public.attendance_location_logs CASCADE;
DROP TABLE IF EXISTS public.attendance CASCADE;
DROP TABLE IF EXISTS public.employee_work_assignments CASCADE;
DROP TABLE IF EXISTS public.work_locations CASCADE;
DROP TABLE IF EXISTS public.registered_devices CASCADE;
DROP TABLE IF EXISTS public.user_sessions CASCADE;
DROP TABLE IF EXISTS public.accounts CASCADE;
DROP TABLE IF EXISTS public.employees CASCADE;
DROP TABLE IF EXISTS public.shifts CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;
DROP TABLE IF EXISTS public.departments CASCADE;

DROP FUNCTION IF EXISTS public.set_updated_at() CASCADE;

/* ============================================================
   1. DEPARTMENTS
   Lưu thông tin phòng ban.
   ============================================================ */
CREATE TABLE public.departments (
    department_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL,
    description     VARCHAR(255),
    status          SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_departments_name
        UNIQUE (department_name),

    CONSTRAINT ck_departments_status
        CHECK (status IN (0, 1))
);

/* ============================================================
   2. ROLES
   Hệ thống sử dụng ba vai trò cố định.
   ============================================================ */
CREATE TABLE public.roles (
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_roles_name
        UNIQUE (role_name),

    CONSTRAINT ck_roles_name
        CHECK (role_name IN ('SUPMANAGER', 'ADMIN', 'MANAGER', 'EMPLOYEE'))
);

/* ============================================================
   3. EMPLOYEES
   Không có shift_id vì hệ thống không quản lý ca.
   ============================================================ */
CREATE TABLE public.employees (
    employee_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code VARCHAR(20) NOT NULL,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(100),
    phone         VARCHAR(20),
    department_id BIGINT NOT NULL,
    status        SMALLINT NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_employees_code
        UNIQUE (employee_code),

    CONSTRAINT fk_employees_department
        FOREIGN KEY (department_id)
        REFERENCES public.departments(department_id),

    CONSTRAINT ck_employees_status
        CHECK (status IN (0, 1)),

    CONSTRAINT ck_employees_email_not_blank
        CHECK (email IS NULL OR BTRIM(email) <> ''),

    CONSTRAINT ck_employees_phone_not_blank
        CHECK (phone IS NULL OR BTRIM(phone) <> '')
);

CREATE INDEX idx_employees_department
ON public.employees(department_id);

CREATE INDEX idx_employees_status
ON public.employees(status);

/* Email được xem là không phân biệt chữ hoa/chữ thường. */
CREATE UNIQUE INDEX uq_employees_email_ci
ON public.employees(LOWER(email))
WHERE email IS NOT NULL;

/* ============================================================
   4. ACCOUNTS
   Mỗi nhân viên có tối đa một tài khoản.
   ============================================================ */
CREATE TABLE public.accounts (
    account_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT NOT NULL,
    username      VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role_id       BIGINT NOT NULL,
    is_active     SMALLINT NOT NULL DEFAULT 1,
    require_password_change BOOLEAN NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_accounts_employee
        UNIQUE (employee_id),

    /* Dùng cho khóa ngoại kết hợp của user_sessions. */
    CONSTRAINT uq_accounts_account_employee
        UNIQUE (account_id, employee_id),

    CONSTRAINT fk_accounts_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(employee_id),

    CONSTRAINT fk_accounts_role
        FOREIGN KEY (role_id)
        REFERENCES public.roles(role_id),

    CONSTRAINT ck_accounts_active
        CHECK (is_active IN (0, 1)),

    CONSTRAINT ck_accounts_username_not_blank
        CHECK (BTRIM(username) <> ''),

    CONSTRAINT ck_accounts_password_hash_not_blank
        CHECK (BTRIM(password_hash) <> '')
);

CREATE INDEX idx_accounts_role
ON public.accounts(role_id);

CREATE INDEX idx_accounts_active
ON public.accounts(is_active);

/* Username không phân biệt chữ hoa/chữ thường. */
CREATE UNIQUE INDEX uq_accounts_username_ci
ON public.accounts(LOWER(username));

/* ============================================================
   5. USER_SESSIONS
   Kiểm soát một tài khoản chỉ có một phiên ACTIVE.
   ============================================================ */
CREATE TABLE public.user_sessions (
    session_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id         BIGINT NOT NULL,
    employee_id        BIGINT NOT NULL,
    device_fingerprint VARCHAR(255) NOT NULL,
    device_name        VARCHAR(255),
    ip_address         VARCHAR(50),
    login_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at         TIMESTAMPTZ NOT NULL,
    logout_at          TIMESTAMPTZ,
    session_status     VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    refresh_token_hash VARCHAR(255),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sessions_account_employee
        FOREIGN KEY (account_id, employee_id)
        REFERENCES public.accounts(account_id, employee_id),

    CONSTRAINT ck_sessions_status
        CHECK (
            session_status IN (
                'ACTIVE',
                'EXPIRED',
                'LOGGED_OUT',
                'REPLACED',
                'REVOKED'
            )
        ),

    CONSTRAINT ck_sessions_expiration
        CHECK (expires_at > login_at),

    CONSTRAINT ck_sessions_last_activity
        CHECK (last_activity_at >= login_at),

    CONSTRAINT ck_sessions_logout_time
        CHECK (logout_at IS NULL OR logout_at >= login_at),

    CONSTRAINT ck_sessions_device_fingerprint_not_blank
        CHECK (BTRIM(device_fingerprint) <> '')
);

/* Một tài khoản chỉ có một phiên ACTIVE tại một thời điểm. */
CREATE UNIQUE INDEX uq_sessions_one_active_per_account
ON public.user_sessions(account_id)
WHERE session_status = 'ACTIVE';

CREATE INDEX idx_sessions_employee
ON public.user_sessions(employee_id);

CREATE INDEX idx_sessions_status
ON public.user_sessions(session_status);

CREATE INDEX idx_sessions_expires_at
ON public.user_sessions(expires_at);

/* ============================================================
   6. REGISTERED_DEVICES
   Lưu lịch sử và trạng thái thiết bị logic đã sử dụng.
   ============================================================ */
CREATE TABLE public.registered_devices (
    device_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id        BIGINT NOT NULL,
    device_fingerprint VARCHAR(255) NOT NULL,
    device_name        VARCHAR(255),
    is_verified        SMALLINT NOT NULL DEFAULT 0,
    registered_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_devices_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(employee_id),

    CONSTRAINT uq_devices_employee_fingerprint
        UNIQUE (employee_id, device_fingerprint),

    CONSTRAINT ck_devices_verified
        CHECK (is_verified IN (0, 1)),

    CONSTRAINT ck_devices_fingerprint_not_blank
        CHECK (BTRIM(device_fingerprint) <> ''),

    CONSTRAINT ck_devices_last_used_time
        CHECK (last_used_at IS NULL OR last_used_at >= registered_at)
);

CREATE INDEX idx_devices_employee
ON public.registered_devices(employee_id);

CREATE INDEX idx_devices_verified
ON public.registered_devices(is_verified);

/* ============================================================
   7. WORK_LOCATIONS
   Lưu địa điểm và bán kính chấm công.
   ============================================================ */
CREATE TABLE public.work_locations (
    location_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name        VARCHAR(100) NOT NULL,
    address              VARCHAR(255),
    latitude             DECIMAL(10,7) NOT NULL,
    longitude            DECIMAL(10,7) NOT NULL,
    allowed_radius_meter INTEGER NOT NULL,
    status               SMALLINT NOT NULL DEFAULT 1,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_locations_latitude
        CHECK (latitude BETWEEN -90 AND 90),

    CONSTRAINT ck_locations_longitude
        CHECK (longitude BETWEEN -180 AND 180),

    CONSTRAINT ck_locations_radius
        CHECK (allowed_radius_meter > 0),

    CONSTRAINT ck_locations_status
        CHECK (status IN (0, 1)),

    CONSTRAINT ck_locations_name_not_blank
        CHECK (BTRIM(location_name) <> '')
);

CREATE INDEX idx_locations_status
ON public.work_locations(status);

/* ============================================================
   8. EMPLOYEE_WORK_ASSIGNMENTS
   Quản trị viên chỉ phân công:
   - nhân viên
   - ngày làm việc
   - địa điểm chấm công
   Không có ca và không có giờ dự kiến.
   ============================================================ */
CREATE TABLE public.employee_work_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT NOT NULL,
    location_id   BIGINT NOT NULL,
    work_date     DATE NOT NULL,
    note          VARCHAR(255),
    status        VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED',
    created_by    BIGINT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    /* Một nhân viên chỉ có một địa điểm được phân công trong một ngày. */
    CONSTRAINT uq_assignments_employee_date
        UNIQUE (employee_id, work_date),

    /* Dùng cho khóa ngoại kết hợp của attendance và logs. */
    CONSTRAINT uq_assignments_context
        UNIQUE (assignment_id, employee_id, work_date),

    CONSTRAINT uq_assignments_assignment_employee
        UNIQUE (assignment_id, employee_id),

    CONSTRAINT fk_assignments_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(employee_id),

    CONSTRAINT fk_assignments_location
        FOREIGN KEY (location_id)
        REFERENCES public.work_locations(location_id),

    CONSTRAINT fk_assignments_creator
        FOREIGN KEY (created_by)
        REFERENCES public.accounts(account_id),

    CONSTRAINT ck_assignments_status
        CHECK (status IN ('ASSIGNED', 'CANCELLED', 'COMPLETED'))
);

CREATE INDEX idx_assignments_location
ON public.employee_work_assignments(location_id);

CREATE INDEX idx_assignments_work_date
ON public.employee_work_assignments(work_date);

CREATE INDEX idx_assignments_status
ON public.employee_work_assignments(status);

/* ============================================================
   9. ATTENDANCE
   Không có is_late, is_early_leave hoặc thông tin ca.
   ============================================================ */
CREATE TABLE public.attendance (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT NOT NULL,
    assignment_id BIGINT NOT NULL,
    work_date     DATE NOT NULL,

    check_in_time  TIMESTAMPTZ,
    check_out_time TIMESTAMPTZ,

    /* Thời gian phía client chỉ dùng tham chiếu, nhất là offline. */
    client_check_in_time  TIMESTAMPTZ,
    client_check_out_time TIMESTAMPTZ,

    check_in_latitude  DECIMAL(10,7),
    check_in_longitude DECIMAL(10,7),
    check_out_latitude DECIMAL(10,7),
    check_out_longitude DECIMAL(10,7),

    check_in_gps_accuracy  DECIMAL(10,2),
    check_out_gps_accuracy DECIMAL(10,2),

    check_in_distance_meter  DECIMAL(10,2),
    check_out_distance_meter DECIMAL(10,2),

    check_in_photo_url  TEXT,
    check_out_photo_url TEXT,

    is_offline_sync     SMALLINT NOT NULL DEFAULT 0,
    location_trust_score INTEGER,
    risk_level           VARCHAR(20),

    attendance_status VARCHAR(30) NOT NULL DEFAULT 'IN_PROGRESS',

    review_status VARCHAR(20) NOT NULL DEFAULT 'NOT_REQUIRED',
    reviewed_by   BIGINT,
    reviewed_at   TIMESTAMPTZ,
    review_note   VARCHAR(500),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    /* Một phân công chỉ có một bản ghi attendance. */
    CONSTRAINT uq_attendance_assignment
        UNIQUE (assignment_id),

    /* Một nhân viên chỉ có một bản ghi attendance trong một ngày. */
    CONSTRAINT uq_attendance_employee_date
        UNIQUE (employee_id, work_date),

    /* Dùng cho khóa ngoại kết hợp của attendance_location_logs. */
    CONSTRAINT uq_attendance_log_context
        UNIQUE (attendance_id, employee_id, assignment_id),

    /* Bảo đảm attendance gắn đúng nhân viên và đúng ngày của assignment. */
    CONSTRAINT fk_attendance_assignment_context
        FOREIGN KEY (assignment_id, employee_id, work_date)
        REFERENCES public.employee_work_assignments(
            assignment_id,
            employee_id,
            work_date
        ),

    CONSTRAINT fk_attendance_reviewer
        FOREIGN KEY (reviewed_by)
        REFERENCES public.accounts(account_id),

    CONSTRAINT ck_attendance_check_in_latitude
        CHECK (
            check_in_latitude IS NULL
            OR check_in_latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT ck_attendance_check_in_longitude
        CHECK (
            check_in_longitude IS NULL
            OR check_in_longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT ck_attendance_check_out_latitude
        CHECK (
            check_out_latitude IS NULL
            OR check_out_latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT ck_attendance_check_out_longitude
        CHECK (
            check_out_longitude IS NULL
            OR check_out_longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT ck_attendance_check_in_accuracy
        CHECK (
            check_in_gps_accuracy IS NULL
            OR check_in_gps_accuracy >= 0
        ),

    CONSTRAINT ck_attendance_check_out_accuracy
        CHECK (
            check_out_gps_accuracy IS NULL
            OR check_out_gps_accuracy >= 0
        ),

    CONSTRAINT ck_attendance_check_in_distance
        CHECK (
            check_in_distance_meter IS NULL
            OR check_in_distance_meter >= 0
        ),

    CONSTRAINT ck_attendance_check_out_distance
        CHECK (
            check_out_distance_meter IS NULL
            OR check_out_distance_meter >= 0
        ),

    CONSTRAINT ck_attendance_offline
        CHECK (is_offline_sync IN (0, 1)),

    CONSTRAINT ck_attendance_trust_score
        CHECK (
            location_trust_score IS NULL
            OR location_trust_score BETWEEN 0 AND 100
        ),

    CONSTRAINT ck_attendance_risk
        CHECK (
            risk_level IS NULL
            OR risk_level IN ('LOW', 'MEDIUM', 'HIGH')
        ),

    CONSTRAINT ck_attendance_status
        CHECK (
            attendance_status IN (
                'IN_PROGRESS',
                'COMPLETED',
                'INVALID',
                'REVIEW_REQUIRED'
            )
        ),

    CONSTRAINT ck_attendance_review_status
        CHECK (
            review_status IN (
                'NOT_REQUIRED',
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        ),

    /* Check-out không được xảy ra trước check-in. */
    CONSTRAINT ck_attendance_time_order
        CHECK (
            check_out_time IS NULL
            OR (
                check_in_time IS NOT NULL
                AND check_out_time >= check_in_time
            )
        ),

    /* Đồng bộ trạng thái attendance với các mốc thời gian. */
    CONSTRAINT ck_attendance_status_time
        CHECK (
            (
                attendance_status = 'IN_PROGRESS'
                AND check_in_time IS NOT NULL
                AND check_out_time IS NULL
            )
            OR (
                attendance_status = 'COMPLETED'
                AND check_in_time IS NOT NULL
                AND check_out_time IS NOT NULL
            )
            OR (
                attendance_status IN ('INVALID', 'REVIEW_REQUIRED')
                AND check_in_time IS NOT NULL
            )
        ),

    /*
       Quy tắc hậu kiểm:
       - REVIEW_REQUIRED phải ở trạng thái PENDING.
       - COMPLETED bình thường dùng NOT_REQUIRED.
       - Sau khi duyệt:
         + APPROVED đi cùng COMPLETED.
         + REJECTED đi cùng INVALID.
    */
    CONSTRAINT ck_attendance_review_consistency
        CHECK (
            (
                attendance_status = 'REVIEW_REQUIRED'
                AND review_status = 'PENDING'
            )
            OR (
                attendance_status = 'COMPLETED'
                AND review_status IN ('NOT_REQUIRED', 'APPROVED')
            )
            OR (
                attendance_status = 'INVALID'
                AND review_status = 'REJECTED'
            )
            OR (
                attendance_status = 'IN_PROGRESS'
                AND review_status = 'NOT_REQUIRED'
            )
        ),

    CONSTRAINT ck_attendance_review_information
        CHECK (
            (
                review_status IN ('NOT_REQUIRED', 'PENDING')
                AND reviewed_by IS NULL
                AND reviewed_at IS NULL
            )
            OR (
                review_status IN ('APPROVED', 'REJECTED')
                AND reviewed_by IS NOT NULL
                AND reviewed_at IS NOT NULL
            )
        ),

    CONSTRAINT ck_attendance_review_note
        CHECK (
            review_note IS NULL
            OR BTRIM(review_note) <> ''
        )
);

CREATE INDEX idx_attendance_status
ON public.attendance(attendance_status);

CREATE INDEX idx_attendance_review_status
ON public.attendance(review_status);

CREATE INDEX idx_attendance_created_at
ON public.attendance(created_at);

/* ============================================================
   10. ATTENDANCE_LOCATION_LOGS
   Lưu dấu vết cho từng request check-in/check-out,
   kể cả request bị từ chối.
   ============================================================ */
CREATE TABLE public.attendance_location_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /* Chống xử lý lặp cùng một payload từ PWA/IndexedDB. */
    client_request_id UUID,

    attendance_id BIGINT,
    employee_id   BIGINT NOT NULL,
    session_id    BIGINT,
    assignment_id BIGINT,
    location_id   BIGINT,

    action_type VARCHAR(20) NOT NULL,

    /* Vị trí nhân viên do client gửi. */
    latitude    DECIMAL(10,7),
    longitude   DECIMAL(10,7),
    gps_accuracy DECIMAL(10,2),

    /* Snapshot địa điểm và bán kính dùng khi xác thực. */
    target_latitude       DECIMAL(10,7),
    target_longitude      DECIMAL(10,7),
    applied_radius_meter  INTEGER,
    distance_meter        DECIMAL(10,2),

    device_fingerprint VARCHAR(255),
    is_pwa_standalone  SMALLINT NOT NULL DEFAULT 0,

    captured_at_client TIMESTAMPTZ,
    received_at_server TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    is_offline_payload SMALLINT NOT NULL DEFAULT 0,

    location_trust_score INTEGER,
    validation_result    VARCHAR(30) NOT NULL,
    validation_reason    VARCHAR(500),
    risk_level           VARCHAR(20),

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    /* Khi attendance_id có giá trị, context phải khớp attendance. */
    CONSTRAINT fk_logs_attendance_context
        FOREIGN KEY (attendance_id, employee_id, assignment_id)
        REFERENCES public.attendance(
            attendance_id,
            employee_id,
            assignment_id
        ),

    CONSTRAINT fk_logs_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(employee_id),

    CONSTRAINT fk_logs_session
        FOREIGN KEY (session_id)
        REFERENCES public.user_sessions(session_id),

    /* Bảo đảm assignment_id thuộc đúng employee_id. */
    CONSTRAINT fk_logs_assignment_employee
        FOREIGN KEY (assignment_id, employee_id)
        REFERENCES public.employee_work_assignments(
            assignment_id,
            employee_id
        ),

    CONSTRAINT fk_logs_location
        FOREIGN KEY (location_id)
        REFERENCES public.work_locations(location_id),

    CONSTRAINT ck_logs_action
        CHECK (action_type IN ('CHECK_IN', 'CHECK_OUT')),

    CONSTRAINT ck_logs_pwa
        CHECK (is_pwa_standalone IN (0, 1)),

    CONSTRAINT ck_logs_offline
        CHECK (is_offline_payload IN (0, 1)),

    CONSTRAINT ck_logs_validation
        CHECK (
            validation_result IN (
                'ACCEPTED',
                'REJECTED',
                'REVIEW_REQUIRED'
            )
        ),

    CONSTRAINT ck_logs_risk
        CHECK (
            risk_level IS NULL
            OR risk_level IN ('LOW', 'MEDIUM', 'HIGH')
        ),

    CONSTRAINT ck_logs_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),

    CONSTRAINT ck_logs_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),

    CONSTRAINT ck_logs_target_latitude
        CHECK (
            target_latitude IS NULL
            OR target_latitude BETWEEN -90 AND 90
        ),

    CONSTRAINT ck_logs_target_longitude
        CHECK (
            target_longitude IS NULL
            OR target_longitude BETWEEN -180 AND 180
        ),

    CONSTRAINT ck_logs_accuracy
        CHECK (gps_accuracy IS NULL OR gps_accuracy >= 0),

    CONSTRAINT ck_logs_distance
        CHECK (distance_meter IS NULL OR distance_meter >= 0),

    CONSTRAINT ck_logs_radius
        CHECK (
            applied_radius_meter IS NULL
            OR applied_radius_meter > 0
        ),

    CONSTRAINT ck_logs_trust_score
        CHECK (
            location_trust_score IS NULL
            OR location_trust_score BETWEEN 0 AND 100
        ),

    /* ACCEPTED phải liên kết với attendance chính thức. */
    CONSTRAINT ck_logs_accepted_attendance
        CHECK (
            validation_result <> 'ACCEPTED'
            OR attendance_id IS NOT NULL
        ),

    /* REJECTED hoặc REVIEW_REQUIRED phải ghi rõ lý do. */
    CONSTRAINT ck_logs_validation_reason
        CHECK (
            validation_result = 'ACCEPTED'
            OR (
                validation_reason IS NOT NULL
                AND BTRIM(validation_reason) <> ''
            )
        ),

    /* ACCEPTED phải có đủ dữ liệu đã dùng để kiểm tra geofence. */
    CONSTRAINT ck_logs_accepted_geofence_data
        CHECK (
            validation_result <> 'ACCEPTED'
            OR (
                latitude IS NOT NULL
                AND longitude IS NOT NULL
                AND gps_accuracy IS NOT NULL
                AND target_latitude IS NOT NULL
                AND target_longitude IS NOT NULL
                AND applied_radius_meter IS NOT NULL
                AND distance_meter IS NOT NULL
                AND assignment_id IS NOT NULL
                AND location_id IS NOT NULL
                AND session_id IS NOT NULL
            )
        )
);

/* Một client_request_id chỉ được xử lý một lần. */
CREATE UNIQUE INDEX uq_logs_client_request_id
ON public.attendance_location_logs(client_request_id)
WHERE client_request_id IS NOT NULL;

CREATE INDEX idx_logs_attendance
ON public.attendance_location_logs(attendance_id);

CREATE INDEX idx_logs_employee
ON public.attendance_location_logs(employee_id);

CREATE INDEX idx_logs_session
ON public.attendance_location_logs(session_id);

CREATE INDEX idx_logs_assignment
ON public.attendance_location_logs(assignment_id);

CREATE INDEX idx_logs_location
ON public.attendance_location_logs(location_id);

CREATE INDEX idx_logs_validation
ON public.attendance_location_logs(validation_result);

CREATE INDEX idx_logs_received_at
ON public.attendance_location_logs(received_at_server);

/* ============================================================
   11. SYSTEM_LOGS
   Nhật ký thao tác và sự kiện quan trọng của hệ thống.
   ============================================================ */
CREATE TABLE public.system_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    employee_id BIGINT,
    account_id  BIGINT,

    action      VARCHAR(100) NOT NULL,
    description VARCHAR(500),

    device_fingerprint VARCHAR(255),
    ip_address         VARCHAR(50),

    status      VARCHAR(20) NOT NULL,
    action_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_system_logs_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(employee_id),

    CONSTRAINT fk_system_logs_account
        FOREIGN KEY (account_id)
        REFERENCES public.accounts(account_id),

    CONSTRAINT ck_system_logs_status
        CHECK (status IN ('SUCCESS', 'FAILED', 'WARNING')),

    CONSTRAINT ck_system_logs_action_not_blank
        CHECK (BTRIM(action) <> '')
);

CREATE INDEX idx_system_logs_employee
ON public.system_logs(employee_id);

CREATE INDEX idx_system_logs_account
ON public.system_logs(account_id);

CREATE INDEX idx_system_logs_action
ON public.system_logs(action);

CREATE INDEX idx_system_logs_status
ON public.system_logs(status);

CREATE INDEX idx_system_logs_action_time
ON public.system_logs(action_time);

/* ============================================================
   12. TRIGGER TỰ ĐỘNG CẬP NHẬT updated_at
   ============================================================ */
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_departments_updated_at
BEFORE UPDATE ON public.departments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_roles_updated_at
BEFORE UPDATE ON public.roles
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_employees_updated_at
BEFORE UPDATE ON public.employees
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_accounts_updated_at
BEFORE UPDATE ON public.accounts
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_sessions_updated_at
BEFORE UPDATE ON public.user_sessions
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_devices_updated_at
BEFORE UPDATE ON public.registered_devices
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_locations_updated_at
BEFORE UPDATE ON public.work_locations
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_assignments_updated_at
BEFORE UPDATE ON public.employee_work_assignments
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_attendance_updated_at
BEFORE UPDATE ON public.attendance
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

/* ============================================================
   13. DỮ LIỆU KHỞI TẠO CƠ BẢN
   ============================================================ */
INSERT INTO public.roles (role_name, description)
VALUES
    ('SUPMANAGER', 'Quản trị viên tối cao'),
    ('ADMIN', 'Quản trị viên hoặc nhân sự'),
    ('MANAGER', 'Quản lý phòng ban'),
    ('EMPLOYEE', 'Nhân viên sử dụng hệ thống chấm công');

/* ============================================================
   14. EMPLOYEE_FACE_PROFILES
   ============================================================ */
CREATE TABLE public.employee_face_profiles (
    face_profile_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT NOT NULL,
    embedding         JSONB NOT NULL,
    embedding_version VARCHAR(30) NOT NULL,
    provider          VARCHAR(100) NOT NULL,
    status            SMALLINT NOT NULL DEFAULT 1,
    registered_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMPTZ,

    CONSTRAINT fk_face_profiles_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(employee_id),

    CONSTRAINT ck_face_profiles_status
        CHECK (status IN (0, 1))
);

CREATE UNIQUE INDEX uq_active_employee_face_profile
ON public.employee_face_profiles(employee_id)
WHERE status = 1;

CREATE INDEX idx_face_profiles_employee
ON public.employee_face_profiles(employee_id);

CREATE TABLE public.employee_webauthn_credentials (
    credential_id           VARCHAR(255) PRIMARY KEY,
    employee_id             BIGINT NOT NULL,
    credential_public_key   TEXT NOT NULL,
    credential_counter      BIGINT NOT NULL DEFAULT 0,
    credential_device_name  VARCHAR(255),
    credential_type         VARCHAR(50) NOT NULL DEFAULT 'public-key',
    transports              JSONB,
    aaguid                  VARCHAR(50),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at              TIMESTAMPTZ,

    CONSTRAINT fk_webauthn_credentials_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(employee_id)
);

CREATE TRIGGER trg_webauthn_credentials_updated_at
BEFORE UPDATE ON public.employee_webauthn_credentials
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

COMMIT;

/* ============================================================
   GHI CHÚ TRIỂN KHAI
   ============================================================

   1. Script này là script khởi tạo lại cấu trúc database.
      Các lệnh DROP TABLE sẽ xóa dữ liệu cũ.

   2. Backend không được tin employee_id, location_id, tọa độ mục tiêu
      hoặc bán kính do frontend gửi lên.

   3. Backend phải xác định nhân viên theo chuỗi:
      Access Token -> user_sessions -> accounts -> employees.

   4. Backend phải xác định địa điểm theo chuỗi:
      assignment_id -> employee_work_assignments -> work_locations.

   5. Attendance chỉ được INSERT sau khi check-in đã vượt qua xác thực
      và check_in_time phải được lấy từ thời gian server.

   6. Check-out cập nhật bản ghi attendance đã tồn tại, không tạo bản ghi mới.

   7. Request bị từ chối không tạo attendance nhưng vẫn phải tạo
      attendance_location_logs với validation_result = 'REJECTED'.

   8. Mỗi payload từ IndexedDB phải giữ nguyên client_request_id
      trong tất cả các lần thử đồng bộ.

   9. Hệ thống không quản lý ca, không đánh giá đi trễ hoặc về sớm.
   ============================================================ */
