-- Migration: Add Shift Management and late/early attendance calculations support

-- 1. Create work_shifts table
CREATE TABLE IF NOT EXISTS public.work_shifts (
    shift_id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_code                   VARCHAR(50) NOT NULL UNIQUE,
    shift_name                   VARCHAR(100) NOT NULL,
    start_time                   TIME NOT NULL,
    end_time                     TIME NOT NULL,
    late_grace_minutes           INTEGER NOT NULL DEFAULT 0,
    early_leave_grace_minutes    INTEGER NOT NULL DEFAULT 0,
    minimum_work_minutes         INTEGER NOT NULL DEFAULT 0,
    is_active                    SMALLINT NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at                   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Insert a default morning shift for existing data compatibility
INSERT INTO public.work_shifts (shift_code, shift_name, start_time, end_time, late_grace_minutes, early_leave_grace_minutes, minimum_work_minutes, is_active)
VALUES ('HC', 'Hành chính', '08:00:00', '17:00:00', 5, 5, 480, 1)
ON CONFLICT (shift_code) DO NOTHING;

-- 3. Add shift_id to employee_work_assignments
ALTER TABLE public.employee_work_assignments ADD COLUMN IF NOT EXISTS shift_id BIGINT;

-- 4. Map existing assignments to the default shift
UPDATE public.employee_work_assignments
SET shift_id = (SELECT shift_id FROM public.work_shifts WHERE shift_code = 'HC' LIMIT 1)
WHERE shift_id IS NULL;

-- 5. Set shift_id to NOT NULL
ALTER TABLE public.employee_work_assignments ALTER COLUMN shift_id SET NOT NULL;

-- 6. Add foreign key constraint for assignment shift_id
ALTER TABLE public.employee_work_assignments
DROP CONSTRAINT IF EXISTS fk_assignments_shift,
ADD CONSTRAINT fk_assignments_shift
FOREIGN KEY (shift_id)
REFERENCES public.work_shifts(shift_id);

-- 7. Add shift-related columns to attendance table
ALTER TABLE public.attendance
ADD COLUMN IF NOT EXISTS shift_id BIGINT,
ADD COLUMN IF NOT EXISTS scheduled_start_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS scheduled_end_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS check_in_status VARCHAR(20) DEFAULT 'ON_TIME',
ADD COLUMN IF NOT EXISTS check_out_status VARCHAR(20),
ADD COLUMN IF NOT EXISTS late_minutes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS early_leave_minutes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS worked_minutes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS overtime_minutes INTEGER DEFAULT 0;

-- 8. Add foreign key constraint for attendance shift_id
ALTER TABLE public.attendance
DROP CONSTRAINT IF EXISTS fk_attendance_shift,
ADD CONSTRAINT fk_attendance_shift
FOREIGN KEY (shift_id)
REFERENCES public.work_shifts(shift_id);

-- 9. Drop and recreate status and review check constraints to allow new shift statuses
ALTER TABLE public.attendance DROP CONSTRAINT IF EXISTS ck_attendance_status_time;
ALTER TABLE public.attendance
ADD CONSTRAINT ck_attendance_status_time
CHECK (
    (
        attendance_status = 'IN_PROGRESS'
        AND check_in_time IS NOT NULL
        AND check_out_time IS NULL
    )
    OR (
        attendance_status IN ('COMPLETED', 'NORMAL', 'LATE', 'LEFT_EARLY', 'LATE_AND_LEFT_EARLY', 'OVERTIME')
        AND check_in_time IS NOT NULL
        AND check_out_time IS NOT NULL
    )
    OR (
        attendance_status IN ('INVALID', 'REVIEW_REQUIRED')
        AND check_in_time IS NOT NULL
    )
);

ALTER TABLE public.attendance DROP CONSTRAINT IF EXISTS ck_attendance_review_consistency;
ALTER TABLE public.attendance
ADD CONSTRAINT ck_attendance_review_consistency
CHECK (
    (
        attendance_status = 'REVIEW_REQUIRED'
        AND review_status = 'PENDING'
    )
    OR (
        attendance_status IN ('COMPLETED', 'NORMAL', 'LATE', 'LEFT_EARLY', 'LATE_AND_LEFT_EARLY', 'OVERTIME')
        AND review_status IN ('NOT_REQUIRED', 'APPROVED')
    )
    OR (
        attendance_status = 'INVALID'
        AND review_status = 'REJECTED'
    )
    OR (
        attendance_status = 'IN_PROGRESS'
        AND review_status = 'NOT_REQUIRED'
    )
);

-- 10. Drop and recreate status check constraint to allow new statuses in column
ALTER TABLE public.attendance DROP CONSTRAINT IF EXISTS ck_attendance_status;
ALTER TABLE public.attendance
ADD CONSTRAINT ck_attendance_status
CHECK (
    attendance_status IN (
        'IN_PROGRESS',
        'COMPLETED',
        'INVALID',
        'REVIEW_REQUIRED',
        'NORMAL',
        'LATE',
        'LEFT_EARLY',
        'LATE_AND_LEFT_EARLY',
        'OVERTIME'
    )
);
