-- Create employee_face_profiles table
CREATE TABLE IF NOT EXISTS public.employee_face_profiles (
    face_profile_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id       BIGINT NOT NULL,
    embedding         JSONB NOT NULL,
    embedding_version VARCHAR(30) NOT NULL,
    provider          VARCHAR(100) NOT NULL,
    status            SMALLINT NOT NULL DEFAULT 1,
    registered_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at        TIMESTAMPTZ,

    CONSTRAINT fk_face_profiles_employee
        FOREIGN KEY (employee_id)
        REFERENCES public.employees(employee_id),

    CONSTRAINT ck_face_profiles_status
        CHECK (status IN (0, 1))
);

-- Index to enforce that only one active profile can exist per employee
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_employee_face_profile
ON public.employee_face_profiles(employee_id)
WHERE status = 1;

CREATE INDEX IF NOT EXISTS idx_face_profiles_employee
ON public.employee_face_profiles(employee_id);
