-- Migration: Create Leave Balances Table
CREATE TABLE IF NOT EXISTS public.leave_balances (
    leave_balance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      BIGINT NOT NULL REFERENCES public.employees(employee_id) ON DELETE CASCADE,
    year             INT NOT NULL,
    
    annual_days_total DECIMAL(4,1) NOT NULL DEFAULT 12.0, -- Số ngày phép năm được cấp
    annual_days_used  DECIMAL(4,1) NOT NULL DEFAULT 0.0,  -- Số ngày phép năm đã nghỉ
    sick_days_used    DECIMAL(4,1) NOT NULL DEFAULT 0.0,  -- Số ngày nghỉ bệnh đã dùng
    unpaid_days_used  DECIMAL(4,1) NOT NULL DEFAULT 0.0,  -- Số ngày nghỉ không lương đã dùng
    marriage_days_used DECIMAL(4,1) NOT NULL DEFAULT 0.0, -- Số ngày nghỉ cưới đã dùng
    maternity_days_used DECIMAL(4,1) NOT NULL DEFAULT 0.0,-- Số ngày nghỉ thai sản đã dùng
    other_days_used   DECIMAL(4,1) NOT NULL DEFAULT 0.0,  -- Số ngày nghỉ khác đã dùng
    
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uq_employee_year_balance UNIQUE (employee_id, year),
    CONSTRAINT ck_leave_balance_year CHECK (year >= 2020)
);

CREATE INDEX IF NOT EXISTS idx_leave_balances_employee ON public.leave_balances(employee_id, year);
