-- Migration: Create Leave Requests Table
CREATE TABLE IF NOT EXISTS public.leave_requests (
    leave_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      BIGINT NOT NULL REFERENCES public.employees(employee_id) ON DELETE CASCADE,
    
    leave_type       VARCHAR(30) NOT NULL, -- ANNUAL, SICK, UNPAID, MARRIAGE, MATERNITY, OTHER, COMPENSATORY
    start_date       DATE NOT NULL,
    end_date         DATE NOT NULL,
    reason           VARCHAR(500) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED, CANCELLED
    
    approved_by      BIGINT REFERENCES public.employees(employee_id) ON DELETE SET NULL,
    approved_at      TIMESTAMPTZ,
    reject_reason    VARCHAR(500),
    
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT ck_leave_dates CHECK (start_date <= end_date),
    CONSTRAINT ck_leave_type CHECK (leave_type IN ('ANNUAL', 'SICK', 'UNPAID', 'MARRIAGE', 'MATERNITY', 'OTHER', 'COMPENSATORY')),
    CONSTRAINT ck_leave_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_leave_requests_employee ON public.leave_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status ON public.leave_requests(status);
CREATE INDEX IF NOT EXISTS idx_leave_requests_range ON public.leave_requests(start_date, end_date);
