-- Migration: Create Overtime Requests Table
CREATE TABLE IF NOT EXISTS public.ot_requests (
    ot_request_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      BIGINT NOT NULL REFERENCES public.employees(employee_id) ON DELETE CASCADE,
    assignment_id    BIGINT NOT NULL REFERENCES public.employee_work_assignments(assignment_id) ON DELETE CASCADE,
    work_date        DATE NOT NULL,
    start_time       TIME NOT NULL,
    end_time         TIME NOT NULL,
    duration_hours   DECIMAL(4,2) NOT NULL,
    reason           VARCHAR(100) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approved_by      BIGINT REFERENCES public.employees(employee_id) ON DELETE SET NULL,
    approved_at      TIMESTAMPTZ,
    reject_reason    VARCHAR(100),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT ck_ot_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    CONSTRAINT ck_ot_time CHECK (start_time < end_time),
    CONSTRAINT ck_ot_duration CHECK (duration_hours > 0.0),
    CONSTRAINT uq_employee_assignment_ot UNIQUE (employee_id, assignment_id)
);

CREATE INDEX IF NOT EXISTS idx_ot_requests_employee ON public.ot_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_ot_requests_assignment ON public.ot_requests(assignment_id);
CREATE INDEX IF NOT EXISTS idx_ot_requests_date ON public.ot_requests(work_date);
CREATE INDEX IF NOT EXISTS idx_ot_requests_status ON public.ot_requests(status);
