CREATE TABLE IF NOT EXISTS public.attendance_photos (
    photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_id BIGINT REFERENCES public.attendance(attendance_id) ON DELETE SET NULL,
    employee_id BIGINT NOT NULL REFERENCES public.employees(employee_id) ON DELETE CASCADE,
    assignment_id BIGINT REFERENCES public.employee_work_assignments(assignment_id) ON DELETE SET NULL,
    photo_type VARCHAR(50) NOT NULL,
    photo_url TEXT NOT NULL,
    public_id VARCHAR(255),
    captured_at TIMESTAMP WITH TIME ZONE,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    cloud_provider VARCHAR(50) DEFAULT 'LOCAL',
    file_size INT,
    mime_type VARCHAR(100),
    image_width INT,
    image_height INT,
    
    -- Siêu dữ liệu AI & GPS phục vụ kiểm toán
    face_confidence DECIMAL(5,2),
    liveness_score DECIMAL(5,2),
    verification_result VARCHAR(50),
    gps_accuracy DECIMAL(10,2),
    gps_distance DECIMAL(10,2),
    
    is_deleted INT DEFAULT 0, -- 0: Active, 1: Soft Deleted
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Ràng buộc photo_type chống sai sót dữ liệu
    CONSTRAINT ck_photo_type CHECK (
        photo_type IN (
            'LOCATION_BEFORE_FACE',
            'LOCATION_CAPTURE',
            'FACE_CAPTURE',
            'CHECK_IN_FINAL',
            'CHECK_OUT_FINAL',
            'OFFLINE_SYNC',
            'MANUAL_REVIEW',
            'ADMIN_UPLOAD'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_attendance_photos_attendance_id ON public.attendance_photos(attendance_id);
CREATE INDEX IF NOT EXISTS idx_attendance_photos_employee_id ON public.attendance_photos(employee_id);
CREATE INDEX IF NOT EXISTS idx_attendance_photos_captured_at ON public.attendance_photos(captured_at);
CREATE INDEX IF NOT EXISTS idx_attendance_photos_photo_type ON public.attendance_photos(photo_type);
