-- Migration: Create Global Notifications Table
CREATE TABLE IF NOT EXISTS public.notifications (
    notification_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id     BIGINT NOT NULL REFERENCES public.employees(employee_id) ON DELETE CASCADE,
    
    module           VARCHAR(50) NOT NULL, -- LEAVE, ATTENDANCE, DEVICE, SECURITY, SYSTEM
    notification_type VARCHAR(50) NOT NULL, -- LEAVE_APPROVED, LEAVE_REJECTED, DEVICE_BLOCKED, ATTENDANCE_WARN
    title            VARCHAR(150) NOT NULL,
    message          TEXT NOT NULL,
    is_read          SMALLINT NOT NULL DEFAULT 0, -- 0: Unread, 1: Read
    
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON public.notifications(recipient_id);
CREATE INDEX IF NOT EXISTS idx_notifications_unread ON public.notifications(recipient_id) WHERE is_read = 0;
CREATE INDEX IF NOT EXISTS idx_notifications_module ON public.notifications(module);
